micronaut:
  application:
    name: transactionKotlinMn
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/rulebase
    driverClassName: org.postgresql.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES
#jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages: com.sharansh
netty:
  default:
    allocator:
      max-order: 3

#kafka:
#  bootstrap:
#    servers: localhost:9092
